Fix: yml 내용 수정

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -45,41 +45,41 @@ jobs:
           docker push ${{ secrets.DOCKER_USERNAME }}/daily_doodle:${{ github.sha }}
           docker push ${{ secrets.DOCKER_USERNAME }}/daily_doodle:be
 
-    deploy:
-      runs-on: ubuntu-latest
-      needs: build
-      if: ${{ github.event_name == 'workflow_dispatch' }}
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ github.event_name == 'workflow_dispatch' }}
 
-      steps:
-        - name: Manual Approval
-          uses: hmarr/auto-approve-action@v2
+    steps:
+      - name: Manual Approval
+        uses: hmarr/auto-approve-action@v2
 
-        - name: Deploy to EC2
-          env:
-            EC2_HOST: ${{ secrets.EC2_HOST }}
-            EC2_USER: ec2-user
-            DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/daily_doodle:${{ github.sha }}
-            KEY_PATH: /tmp/deploy_key.pem
-          run: |
-            echo "${{ secrets.EC2_SSH_KEY }}" > $KEY_PATH
-            chmod 400 $KEY_PATH
-              #EC2 서버의 호스트 키를 known_hosts 파일에 추가
-              ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
-              #SSH로 EC2에 접속하고 배포 작업 수행
-              ssh -o StrictHostKeyChecking=yes -i $KEY_PATH $EC2_USER@$EC2_HOST <<EOF
+      - name: Deploy to EC2
+        env:
+          EC2_HOST: ${{ secrets.EC2_HOST }}
+          EC2_USER: ec2-user
+          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/daily_doodle:${{ github.sha }}
+          KEY_PATH: /tmp/deploy_key.pem
+        run: |
+          echo "${{ secrets.EC2_SSH_KEY }}" > $KEY_PATH
+          chmod 400 $KEY_PATH
+            #EC2 서버의 호스트 키를 known_hosts 파일에 추가
+            ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
+            #SSH로 EC2에 접속하고 배포 작업 수행
+            ssh -o StrictHostKeyChecking=yes -i $KEY_PATH $EC2_USER@$EC2_HOST <<EOF
 
-              # 배포 전 docker 설치 확인
-              if ! command -v docker &> /dev/null
-              then
-                echo "Docker could not be found, installing Docker..."
-                sudo apt-get update
-                sudo apt-get install -y docker.io
-              fi
-              # Pull the new Docker image
-              docker pull $DOCKER_IMAGE
-              docker stop app || true
-              docker rm app || true
-              docker run -d --name app -p 80:80 $DOCKER_IMAGE
-              # 배포 후 확인
-              curl --fail http://$EC2_HOST:80 || exit 1
-            EOF
+            # 배포 전 docker 설치 확인
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker could not be found, installing Docker..."
+              sudo apt-get update
+              sudo apt-get install -y docker.io
+            fi
+            # Pull the new Docker image
+            docker pull $DOCKER_IMAGE
+            docker stop app || true
+            docker rm app || true
+            docker run -d --name app -p 80:80 $DOCKER_IMAGE
+            # 배포 후 확인
+            curl --fail http://$EC2_HOST:80 || exit 1
+          EOF
